### PR TITLE
Add ping_interval and ping_max to ProcessConfigFile

### PR DESCRIPTION
**Pull request by Jeraimee**
Added missing ping_interval and ping_max options.

### CODE REVIEW

**Comment by mcqueary** [comment]
Hi @Jeraimee: we're in the home stretch on this thing, can you go ahead and add a test case to this PR? Thanks!

**Comment by derekcollison** [comment]
If you could add a test we could bring this one in. Thanks.

**Comment by Jeraimee** [comment]
Sorry for the delay! I'll try to add test cases this weekend!

**Comment by kozlovic** [comment]
@Jeraimee It has been a long time. It seems that there is similar interest: https://github.com/nats-io/gnatsd/issues/370. Do you think you will be able to contribute a test case?

**Comment by Jeraimee** [comment]
I forgot all about it! Sorry! I'm working with gnatsd this weekend so I'll take care of it by Sunday.

**Comment by kozlovic** [comment]
@Jeraimee Sorry, @vkhorozvs submitted a PR based on yours with tests and we have merged his: https://github.com/nats-io/gnatsd/pull/372. Closing this one.
Thanks again for the original contribution!

**Comment by Jeraimee** [comment]
No problem. I'm glad someone took care of it. I've had too much work/family/pet drama. My apologies.

**Pull request closed without merging**
