### PR TITLE
Add optional override of cipher suites

### PR DESCRIPTION
**Pull request by ColinSullivan1**
This allows clients in older environments (e.g. .NET clients on windows 7) to use TLS.

### CODE REVIEW

**Comment by ColinSullivan1** [comment]
Missed the test...  I'll resubmit in a bit.

**Comment by ColinSullivan1** [comment]
Looks like an unrelated test is failing... This test passes locally for me, and passed with GO 1.4 in travis.

--- FAIL: TestClusterQueueSubs (0.11s)
	<autogenerated>:33: Did not get correct # msgs: 1 vs 5

**Comment by ColinSullivan1** [comment]
Per conversations with our security experts, I've changed direction here:  Users must specify cipher suites in the configuration, and we do not provide defaults to avoid the future possibility of having outdated cipher suites hardcoded anyplace.

In anticipation of the additional configuration step, I've updated help to assist with TLS configuration, adding a -help_tls command line parameter.

**Comment by derekcollison** [comment]
Let's not go this direction. I do not want to require a config, and I want to have some sane defaults that are future proof enough without requiring a config file. We should be as trusted as we can (use newer cipher suites), and require it to be harder to configure to allow insecure ones.

**Comment by derekcollison** [comment]
I do like being able to additionally configure cipher suites via config, so let's keep that.

**Comment by ColinSullivan1** [comment]
I removed the requirement for cipher_suites (it's optional now), reverted changes to the test files, and restored the defaults, to their original settings:  TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 and TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.  Hopefully we're set, but I'm happy to make any other changes if need be.

**Comment by derekcollison** [comment]
You may have to do a specific merge on your side now since I landed the TLS updates. Hopefully straightforward.

**Comment by ColinSullivan1** [comment]
Will do...

**Comment by ColinSullivan1** [comment]
* Merged the recent master branch changes into this branch
 * Moved the cipher maps to the go version specific files

**Pull request merged**
