### PR TITLE
[CHANGED] Cluster permissions moved out of cluster's authorization

### PR DESCRIPTION
**Pull request by kozlovic**
It will be possible to set subjects permissions regardless of the
presence of an authorization block.

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Comment by kozlovic** [comment]
@derekcollison @wallyqs This PR will probably conflict with #745. So either 745 goes first and I'll rebase and update to match the new behavior, or this one goes first and Wally will have to do the equivalent in 745. What do you guys think?

**Comment by wallyqs** [comment]
Thanks @kozlovic this PR is smaller so I think I'd rather have this one merged first and then rebase #745 on top with the new logic.

**Comment by kozlovic** [comment]
@wallyqs Ok, will merge. What I would like is that in pedantic mode we report a warning if permissions are set in the auth block and ask that users move it out, like a deprecated thing if you will. Do you think that makes sense and possible in #745?

**Comment by wallyqs** [comment]
yes I think that sounds good, while checking the configuration we could make it error and exit 1 when facing a deprecated field, or was thinking that could try to make it collect the warnings and display them before exiting 0 if no other errors. Could be just to print to stderr maybe, similar to time duration handling: https://github.com/nats-io/gnatsd/blob/master/server/opts.go#L343

**Pull request merged**
