### PR TITLE
[ADDED] Server id to connz and routez

### LINKED ISSUE #490: Server ID is not available on JSONs other than /varz
- [X] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

Without the server id, there's no indication of whether the server restarted.
 
#### Versions of `gnatsd` and affected client libraries used:

All

#### OS/Container environment:

All

#### Steps or code to reproduce the issue:

See /varz, has `server_id` other JSONs don't.

#### Expected result:

`server_id` should be in all the JSONs.
 
#### Who Benefits From The Change(s)?

Monitoring tools.
 
#### Alternative Approaches

Time comparisons

### PR DESCRIPTION
**Pull request by aricart**
- [x] Link to issue, e.g. `Resolves #NNN`
 - [x] Tests added
 - [x] Branch rebased on top of current master (`git pull --rebase origin master`)
 - [x] Changes squashed to a single commit
 - [x] Build is green in Travis CI

Resolves #490  

### Changes proposed in this pull request: 

 - Adds additional information (the server id) to the JSON that enables tools to associate a particular server process without having to look at the `now` information.

### CODE REVIEW

**Comment by aricart** [comment]
This is useful for NATS cloud - insured that the reading of server.info.ID is done under the same lock acquired by connz/routez.

**Comment by ColinSullivan1** [comment]
Just following up, are we waiting on anything here?

**Comment by kozlovic** [comment]
@ColinSullivan1 Seem that there is a conflict to resolve in order to merge. Also, @derekcollison  may want to weigh on this addition.

**Comment by derekcollison** [comment]
Let's resolve conflicts, don't see any issues with it. Could be useful for stateful applications. They can now understand a restart event.

**Pull request merged**
