### PR TITLE
Fix leaking log output in unit tests

### PR DESCRIPTION
**Pull request by tylertreat**
```
go test -race -v -run="TestConfigReload|TestSignal" ./server
=== RUN   TestConfigReloadNoConfigFile
--- PASS: TestConfigReloadNoConfigFile (0.00s)
=== RUN   TestConfigReloadUnsupported
--- PASS: TestConfigReloadUnsupported (0.00s)
=== RUN   TestConfigReloadInvalidConfig
--- PASS: TestConfigReloadInvalidConfig (0.00s)
=== RUN   TestConfigReload
--- PASS: TestConfigReload (0.01s)
=== RUN   TestConfigReloadRotateTLS
--- PASS: TestConfigReloadRotateTLS (0.97s)
=== RUN   TestConfigReloadEnableTLS
--- PASS: TestConfigReloadEnableTLS (0.27s)
=== RUN   TestConfigReloadDisableTLS
--- PASS: TestConfigReloadDisableTLS (0.26s)
=== RUN   TestSignalToReOpenLogFile
--- PASS: TestSignalToReOpenLogFile (0.53s)
PASS
ok      github.com/nats-io/gnatsd/server        3.289s
```

@derekcollison @kozlovic

### CODE REVIEW

**Comment by kozlovic** [comment]
LGTM

**Comment by derekcollison** [comment]
If you do not need the logs, you can mute them in the tests instead of redirecting to a file.

**Comment by derekcollison** [comment]
Look for NoLog option to start the server. By default most tests use this option to suppress logs unless you need to verify log output.

**Comment by tylertreat** [comment]
I'm confused by the `NoLog` option. AFAICT `NoLog` has no usages in the code base, only assignments (and only in tests). The parser also does not parse it. Where/how is `NoLog` used?

**Comment by derekcollison** [comment]
Only useful for tests.

**Comment by tylertreat** [comment]
But I can't find any cases where `NoLog` is read, either in tests or source code. It's only written. I grepped the entire source tree for usages.

**Comment by derekcollison** [comment]
I would imagine someone accidentally removed checking it then..

**Comment by kozlovic** [comment]
@derekcollison @tylertreat NoLog was added by someone at https://github.com/nats-io/gnatsd/commit/2b856275c49bc8084576b87c0957fa89ee929fc5 and removed with this commit https://github.com/nats-io/gnatsd/commit/96d044dce40d5ff00fc0641cfde897d882a574d2 back in Oct 7, 2014

**Comment by derekcollison** [comment]
ok so I think what happened was the nilLogger was supported and default. So the printf you did could be to a Logger if you wanted but would not print, and be default maybe server was not setting up for tests so that is why we never see output?

**Comment by kozlovic** [comment]
Lately, we would not see any output because of the use of a global logger that was only set from the main.go. So no test would ever produce logs. (Server.Errorf() would see that global logger's logger is nil and so would not print anything).
Now server holds a structure (always initialized) and set the actual logger only when calling ConfigureLogger in main.go .. and in reload config for debug/trace, etc... We could always put back the NoLog into the logger itself and do nothing if `log.logger == nil || log.noLog`. The `SetLogger()` could accept another boolean for the options.NoLog.

**Comment by derekcollison** [comment]
@kozlovic @tylertreat will let you two figure out best course forward.

**Comment by tylertreat** [comment]
We should either remove `NoLog` fully or add back support for it. Currently, there are a bunch of references to it but it doesn't do anything, which is pretty confusing. I don't have a string opinion either way, though the least amount of code seems like just not configuring a logger. https://github.com/nats-io/gnatsd/blob/master/server/log.go#L151

**Comment by kozlovic** [comment]
@tylertreat Agreed in that we may not need a NoLog and simply not configure the logger. But as you can see, in the case of config reload, you are forced to do that and this is producing a log. Now, as you did, you can configure to use a file and discard it in the test.
As you know, I am working on merging those changes with Streaming, and I took a different approach in that the configuration of the logger is not exposed and done inside the RunServerX() (I don't have a New() and Start() in streaming). For backward compatibility, I am adding a EnableLogging option that causes RunServer to set the logger. In one test, I was testing that RunServer() would print something to the log if it failed to start. Previously, I would configure the logger, replace it with a dummy one, then call RunServer() and check that it produces the expected output. I would not be able to do this the way I described above, so I added a server option which is CustomLogger and now, I can create my dummy logger, set it in the options and then call RunServer() and it works as expected. Note that for this test I could not use the file logger (to suppress output) because any real logger on Fatalf() call os.Exit() which would cause the test suite to stop. I will commit a branch for Streaming so you can have a look.

**Comment by tylertreat** [comment]
Do we agree that logging changes are outside the scope of this PR? This PR will suppress the log output in the tests, but no-op logging can be made in a separate PR.

**Comment by kozlovic** [comment]
@tylertreat Yes, of course. This PR is LGTM.

**Comment by derekcollison** [comment]
Agree, separate PR.

**Pull request merged**
