### PR TITLE
[ADDED] Ability to suppress echos from your own connection

### LINKED ISSUE #453: Prevent delivery of messages to sending connection's subscriptions
If a client connection's `CONNECT` protocol contains (e.g.) `no_local : true`, the server should not deliver messages that originated from that connection to subscriptions on that connection.

- [ ] Add option to clients

### PR DESCRIPTION
**Pull request by derekcollison**
Resolves #453 

/cc @nats-io/core

### CODE REVIEW

**Comment by derekcollison** [comment]
I want to check on how clients interact with older server. May want to bump proto like we did for async INFO to allow clients to check before sending and not getting the result they want.

**Comment by kozlovic** [comment]
Ok, that would work on a connect where we can fail the connection saying that the server is not supporting that feature, but for a reconnect, what do we do? Say you connect to a server supporting echo, then it stops and the next server does not. Do you fail the reconnect?

**Comment by derekcollison** [comment]
I would expect that to be a rare situation, but let me think about it. Client could through async err indicating echo not supported on connected server. More client work I think.

**Comment by aricart** [comment]
the main issue with this feature being a client option is that, if the server doesn't provide the feature, and the option is set, the client will have to raise an error and still cope with the lack of the feature. The error can be mitigated if the client configuration specifies `required` vs `optional`, the client can progress on the connection, but the duplicate messages will be received (behaviour since the beginning of time).

If this setting was a server configuration that is transmitted to the client, existing clients would break, but the fix is one that the client could handle automatically by creating a second connection where those subscriptions can be processed. In my mind, this is an easier paradigm to migrate code.

**Pull request merged**
