### PR TITLE
Use DefaultOptions as function that produces new Options on every call

### PR DESCRIPTION
**Pull request by nogoegst**
- [X] Link to issue, e.g. `Resolves #NNN`
 - [X] Documentation added (if applicable)
 - [X] Tests added
 - [X] Branch rebased on top of current master (`git pull --rebase origin master`)
 - [X] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [ ] Build is green in Travis CI
 - [X] You have certified that the contribution is your original work and that you license the work to the project under the [MIT license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)

### Changes proposed in this pull request: 
 - Corresponding fixes for https://github.com/nats-io/go-nats/pull/308

 
/cc @nats-io/core

### CODE REVIEW

**Comment by nogoegst** [comment]
I guess go-nats should be vendored for CI build to pass.

**Comment by kozlovic** [comment]
Let's wait until we resolve the go-nats PR. I don't think we will vendor the go client just because of the tests.

**Comment by nogoegst** [comment]
@kozlovic Yes, it is meant to be complementary. And failed CI is fine.

**Comment by kozlovic** [comment]
@nogoegst Now that the PR in go-nas is merged (and changed to `GetDefaultOptions()`), would you mind updating this PR? Thanks!

**Comment by nogoegst** [comment]
@kozlovic Done.

**Pull request merged**
