### PR TITLE
experimental: reorg code to move server as gnatsd base package + cmd/gnatsd main

### PR DESCRIPTION
**Pull request by pkieltyka**
I took a pass on #106 for some feedback/thought. This PR encourages the gnatsd server to be embedded in application services utilizing nats - turning nodes into brokers as well, with the goal for nats to be a layer for building distributed services baked right into the service layer.

I also wrote a basic example using this PR - https://gist.github.com/pkieltyka/049266c307bc8f14ea65. It's not that interesting yet.

This PR includes:
- Moved `/gnatsd/server` package to `/gnatsd` and moved the main() in server to `/cmd/gnatsd` 
- A new Makefile to build the server: `make build` to run tests: `make test`
- All tests pass

### CODE REVIEW

**Comment by derekcollison** [comment]
Thanks, will have @krobertson and @olegshaldybin take a quick look.

**Comment by pkieltyka** [comment]
cool. btw, seems to be some minor configuration issue with coveralls in this branch, but I am sure its easily solvable I just never used coveralls.

**Comment by krobertson** [comment]
@pkieltyka overall it looks good... will review it a bit further. We have a few outside parts to update. Namely, I'll take a look at the `Dockerfile` since I think it needs updating to build the right file, and our outside system which builds the binaries on the releases tab.

Don't worry about the Coveralls bit... it looks like with the move, some some code that counted as covered is not in a package that has no tests. Looking it over, there are no functional changes, and it is only 0.3%.

**Comment by pkieltyka** [comment]
@krobertson nice, glad to hear it! `go get github.com/nats-io/gnatsd/cmd/gnatsd` would work as well.

**Comment by pkieltyka** [comment]
@krobertson any chance for further review / consideration? lmk for suggestions and I can tweak

**Comment by nkev** [comment]
@pkieltyka Did you get a chance to tweak to pass tests?

**Comment by mcqueary** [comment]
More recent changes in gnatsd render this PR obsolete. Let's reopen/discuss via a new Issue if you feel parts of this PR are still relevant.

**Pull request closed without merging**
