### PR TITLE
Add dynamic user authentication

### PR DESCRIPTION
**Pull request by gaozhidf**
**Dynamic-user authentication**

You can enable dynamic-user authentication using a NATS server configuration file, that allows you to use both multiuser-auth and token-auth. At the same time,  `authenticator` defines to get your permissions from another NATS server by `authenticator_hub`. To enable dynamic-user authentication, you need to set `dynamic_user` as true.

```
dynamic_user: true

authenticator_hub = [
  $oauth2_authenticator
]

users = [
  {user: alice, password: foo, permissions: $super_user}
  {user: bob,   password: bar, permissions: $req_pub_user}
  {user: susan, password: baz}
  {user: super, password: super, permissions: $super_user}
  {token: foo, permissions: $oauth2_user}
  {user: regex("vincent(.*)"), password: foo, authenticator:"oauth.replier"}
  {user: wildcard("zhigao.*"), password: foo, authenticator:"oauth2.replier"}
  {token: zhigao*, authenticator:"oauth2.replier"}
]
```

For example:

```
dynamic_user: true

oauth2_authenticator1_url = "nats://localhost:4333"
oauth2_authenticator2_url = "nats://alice:foo@localhost:4222"
oauth2_authenticator3_url = "nats://localhost:4222"

authenticator_hub = [
  $oauth2_authenticator1_url
  $oauth2_authenticator2_url
  $oauth2_authenticator3_url
]

PASS: $2a$11$b0PUYclUQ3YOdqI3PkosC.tbbmTTAUCKb5xJwFtQIokrxPFeiIoae

users = [
  {user: alice, password: foo, permissions: $ADMIN}
  {user: bob,   password: bar, permissions: $REQUESTOR}
  {token: foo, permissions: $PASS}
  {user: regex("vincent(.*)"), password: foo, authenticator:"oauth.replier"}
  {user: wildcard("zhigao.*"), password: foo, authenticator:"oauth2.replier"}
  {token: 2323*, authenticator:"oauth3.replier"}
]
```

And if you enable your user authentication with `authenticator`, such as `oauth.replier`. For example, for user `vincent.1`, when he requests to connect a NATS reply server using this configuration file, the reply server will request another NATS server defined by `authenticator_hub` with the payload as below. If authentication succeeded, the reply server will return the same password and token with customized permission.

```
{
  "user": "vincent.1",
  "password": "foo",
  "permissions": {
    "subscribe": [
      "req.foo"
    ],
    "publish": [
      "req.foo",
      "req.bar"
    ]
  },
  "authenticator": "oauth.replier",
  "token": ""
}
```

**Function Test**
You can test dynamic-user authentication using client_auth_test.go, which can be found in gnastd/test
```
cd gnastd/test
go test -v test.go client_auth_test.go
```

### CODE REVIEW

**Comment by ColinSullivan1** [comment]
@gaozhidf,

Thank you for the pull request!  Your code quality looks great, and thank you for providing a thorough unit test.

I can tell a lot of work went into this!  Let’s step back to look at what is being accomplished in this PR. There are quite a few changes here; I suggest separating these features/enhancements into different pull requests:

1)  Adding token support into multi-user authentication.
2)  Referring authorization to a different server using regex and wildcards to direct auth checking to another NATS server.

IMO adding tokens into multi-user authentication is a good idea, and expands functionality without sacrificing performance or adding much complexity.

Can you share your use case for the authenticator hub portion of this?

I ask because there may be other ways to accomplish your goals.  There are quite a few corner cases and areas to look closely at for this type of feature - one would want to support TLS, restrict wildcard/regex matching to only auth hubs, check for circular references, then measure and mitigate performance impacts.  I can see how wildcards can be used to logically distribute credential checking to other NATS servers (reminiscent of LDAP referral chasing), but that can leave a lot of room for user error.  We do have some upcoming features around authorization that may address some of your requirements.

Again, thanks for this PR; we’d really like to hear more of the requirements behind your work here to further discuss.

**Comment by wenzheng** [comment]
@ColinSullivan1 , we are using NATS server as a web messaging component for the exposure of our IoT data, so there will be several internal component work as publisher/replier (see the Data server below) to share the data, and we expect the applications will use tokens to access the data thru NATS server, in our case the tokens are supposed to be exchanged by our own Oauth service.

Maybe the diagram below can help to illustrate what we want to achieve, please check and if you and any question, please dont hesitate to contact us.

alternative text

**Comment by ColinSullivan1** [comment]
This is impressive, and again, thank you for the pull request!  

However, at this time we plan to keep NATS authentication as it is, but may reference this in the future.

You can leverage most of your work by creating a process that creates a server and sets the authentication method to `DynamicUser` with `Server.SetClientAuthMethod` (just as you did in the PR).

A place to look at how this can be done are in the tests; some code to reference is [here](https://github.com/nats-io/gnatsd/blob/master/test/auth_test.go#L110) and [here](https://github.com/nats-io/gnatsd/blob/master/test/test.go#L94).

If you have any questions, please don't hesitate to ask.

**Comment by wenzheng** [comment]
Sure, if you have any plan to enhance the authentication function, please tell us, NATS is great and we are happy working with it.

**Comment by ColinSullivan1** [comment]
Absolutely, and thanks again!

Another reference to encapsulating gnatsd in another process is the [NATS streaming server](https://github.com/nats-io/nats-streaming-server/blob/master/server/server.go#L797).

**Pull request closed without merging**
