### PR TITLE
Adds command line options for clustering 

### PR DESCRIPTION
**Pull request by haseebq**

### CODE REVIEW

**Comment by haseebq** [comment]
I wasn't sure what to name them. The reason I choose "cluster_xxxx" was because these options are configured in the 'cluster' section of the conf file - so it'd be easy to understand what these command line options are configuring. That said - I'm okay either way. Let me know if you want me to change it to routes_xxxx.

**Comment by derekcollison** [comment]
I thought about it more, you are right..

**Comment by derekcollison** [comment]
maybe add something to --routes, like --cluster_routes or --solicit_routes
as an alias..

**Comment by haseebq** [comment]
Not sure I completely understand. So collapse the 4 options (cluster_user, cluster_pass, cluster_addr, cluster_port) into one option that takes in a route URL. i.e:

--cluster_routes nats-route://user1:pass1@0.0.0.0:4333 ?

**Comment by derekcollison** [comment]
I was not suggesting that, although that might be the right way to go
--cluster-listen nats-route://ruser:pass@0.0.0.0:6222

**Comment by derekcollison** [comment]
This is in the current release for connecting to seeds.

**Pull request closed without merging**
