### PR TITLE
Reduce startup memory for gateways

### PR DESCRIPTION
**Pull request by kozlovic**
Similar to #956 but for gateways code.

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Comment by kozlovic** [comment]
@derekcollison Yes, route test (which I copied from) is incorrect because we compare `used` in MB vs `max` in bytes. Should I include the fix in this PR?

**Comment by derekcollison** [comment]
Yes pls.

**Comment by kozlovic** [comment]
I would need to rebase since I believe this branch was created prior to the route merge.

**Comment by derekcollison** [comment]
ok maybe small PR after then.

**Comment by kozlovic** [comment]
No, I have rebased and will update.

**Pull request merged**
