### PR TITLE
[FIXED] Use of `*` and `>` in subjects as literals

### LINKED ISSUE #558: Is this a bug or not?
Hi All:
I got a strange problem, when subject is something like xx.9999,\*,\*,1, when sub and pub restart, sub cant't receive anything on xx.9999,\*,\*,1 it can be reproduce by following step, please notice the start and stop sequence
Env is 
Win7 x86
gnatsd 1.0.2
go-nats is lastest version by go get

1.start gnatsd  
2.start sub  
3.start pub   

*sub will receive 5 msg it's ok             
            
4.close pub  
5.close sub  
6.start sub  
7.start pub  

*now sub cant receive any msg..??  

8.restart gnatsd  
it's work again, but when follow step2 it's not working again.  
if the subscription is invalid, the api should return IsValid() = false??, but if it's invalid, why it works first time?

here is sample code  

sub code
```
package main

import (
	"fmt"

	"github.com/nats-io/nats"
)

func main() {
	nc, err := nats.Connect("nats://127.0.0.1:4222")

	s, err := nc.Subscribe("xx.9999,*,*,1", func(m *nats.Msg) {

		fmt.Println(string(m.Data))
	})
	fmt.Printf("s.IsValid()=%v\n", s.IsValid())

	fmt.Printf("Subscribe err=%v\n", err)
	nc.Flush()
	var buf string
	fmt.Scanf("%s", buf)
}

```

pub code
```
package main

import (
	"github.com/nats-io/nats"

	"fmt"
)

func main() {

	nc, _ := nats.Connect("nats://127.0.0.1:4222")

	for i := 0; i < 5; i += 1 {
		err := nc.Publish("xx.9999,*,*,1", []byte("test xx.9999,*,*,1"))
		fmt.Printf("publish err=%v\n", err)
	}

	nc.Flush()
	var buf string
	fmt.Scanf("%s", buf)
}

```

### PR DESCRIPTION
**Pull request by kozlovic**
The issue was that a subject such as `foo.bar,*,>` would be
inserted to the cache as is, but when trying to remove from the
cache, calling matchLiteral() with the above subject in the cache
against the same subject would return false. This is because
matchLiteral would treat those characters as wildcards token.

Note that the sublist itself splits subjects on the `.` separator
and seem not bothered by such subject (would have `foo` and `bar,*,>`
tokens). Also, note that IsValidSubject() and IsValidLiteralSubject()
properly checked that the characters `*` and `>` are treated
as wildcards only if they are tokens on their own.

Resolves #558

/cc @derekcollison if you could have a look to see if this makes sense, thanks!

### CODE REVIEW

**Comment by derekcollison** [comment]
Does this have a noticeable impact on that functions performance? Should we track separators and token length to make the checks more straightforward?

**Comment by kozlovic** [comment]
Will look into make it faster. But yes, there is an impact as it is now.

But fundamentally, do you agree that `matchLiteral("foo,*,>", "foo,*,>")`
should return `true` because both strings are literals? (current behavior
is that second param of the function will be interpreting the `*` and `>`
as wildcards and therefore return `false`).

**Comment by derekcollison** [comment]
Yes I agree, but want to be sensitive to performance impacts.

**Comment by kozlovic** [comment]
Agreed.. working on optimizations, but difficult to be as fast as with old code since it was not checking that `*` or `>` were single tokens. Still making some improvements and adding a benchmark test. Will update the PR later.

**Comment by derekcollison** [comment]
I think the trick may be in tracking "." separators and keeping separate
count on token length, if when you see next ".", or end of subject, etc.
then and only then to you check for pwc or fwc.

**Comment by kozlovic** [comment]
I think I tried that but it was slow, will try again. Anytime we check ahead (even if we know that it is in bound, assembly code shows that there is a bound check with possible invocation of panicindex()).

**Comment by kozlovic** [comment]
I am going to push a change that includes a small optimization, simplification of 'if' statements and a benchmark test. Will continue trying to optimize. Let's not merge for now.

**Comment by kozlovic** [comment]
Impact on normal bench is not visible. This is a comparison between master and the branch in 1 run only: (note negative value means branch (new) is faster)
```
Ivans-MacBook-Pro:gnatsd ivan$ benchcmp master.txt branch.txt 
benchmark                         old ns/op     new ns/op     delta
Benchmark_____Pub0b_Payload-8     86.8          86.2          -0.69%
Benchmark_____Pub8b_Payload-8     87.2          87.0          -0.23%
Benchmark____Pub32b_Payload-8     95.1          96.3          +1.26%
Benchmark___Pub128B_Payload-8     122           116           -4.92%
Benchmark___Pub256B_Payload-8     180           152           -15.56%
Benchmark_____Pub1K_Payload-8     239           227           -5.02%
Benchmark_____Pub4K_Payload-8     1131          1127          -0.35%
Benchmark_____Pub8K_Payload-8     2292          2314          +0.96%
Benchmark_AuthPub0b_Payload-8     179           175           -2.23%
Benchmark____________PubSub-8     178           177           -0.56%
Benchmark____PubSubTwoConns-8     178           178           +0.00%
Benchmark____PubTwoQueueSub-8     201           200           -0.50%
Benchmark___PubFourQueueSub-8     200           204           +2.00%
Benchmark__PubEightQueueSub-8     201           199           -1.00%
Benchmark___RoutedPubSub_0b-8     496           486           -2.02%
Benchmark___RoutedPubSub_1K-8     1044          1096          +4.98%
Benchmark_RoutedPubSub_100K-8     77286         78541         +1.62%

benchmark                         old MB/s     new MB/s     speedup
Benchmark_____Pub0b_Payload-8     126.75       127.58       1.01x
Benchmark_____Pub8b_Payload-8     218.00       218.39       1.00x
Benchmark____Pub32b_Payload-8     462.85       456.83       0.99x
Benchmark___Pub128B_Payload-8     1154.74      1212.86      1.05x
Benchmark___Pub256B_Payload-8     1488.72      1766.16      1.19x
Benchmark_____Pub1K_Payload-8     4335.65      4558.20      1.05x
Benchmark_____Pub4K_Payload-8     3631.12      3646.54      1.00x
Benchmark_____Pub8K_Payload-8     3579.30      3545.01      0.99x
Benchmark_AuthPub0b_Payload-8     61.18        62.71        1.03x
```
I ran the test another time and the `Benchmark___Pub256B_Payload-8` run is also around 15% faster, not sure why.

@derekcollison

**Comment by derekcollison** [comment]
LGTM

**Pull request merged**
